# Enter the number of pairs
number_of_pairs: 10

# Enter the number of offsprings
kids: 3

# Enter the population name
# ex. "якуты" or "тувинцы"
population: "якуты"

# Enter the frequency of STR-locus mutation
mut_rate: 0.0045